config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'web/articles#index'

  scope module: :web do
    resources :articles do
      scope module: :articles do
        resources :comments, only: [:create, :destroy]
      end
      patch :publish, on: :member
      patch :archive, on: :member
    end
    namespace :admin do
      resources :articles, except: [:create, :new] do
        patch :publish, on: :member
        patch :archive, on: :member
      end

      resources :comments, only: [:index] do
        scope module: :comments do
          resource :rating, only: [:update]
        end
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include ArticleStateMachine

  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy, class_name: 'Article::Rating'
  belongs_to :category, inverse_of: :articles, class_name: 'Article::Category', foreign_key: :article_category_id
  belongs_to :user, inverse_of: :articles

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :article_category_id, presence: true
  validate :valid_category?

  def valid_category?
    return unless current_category.nil?

    errors.add(:category, :not_exist)
  end

  def set_archived_at
    self.archived_at = Time.current
  end

  private

  def current_category
    @current_category ||= Article::Category.find_by(id: article_category_id)
  end
end

app/models/article/category.rb
# frozen_string_literal: true

class Article::Category < ApplicationRecord
  has_many :articles, inverse_of: :category, foreign_key: :article_category_id, class_name: 'Article', dependent: :destroy

  validates :name, presence: true
end

app/models/article/rating.rb
# frozen_string_literal: true

class Article::Rating < ApplicationRecord
  belongs_to :article, inverse_of: :ratings, class_name: 'Article'

  validates :sum_of_ratings, presence: true
  validates :rating, presence: true
  validates :is_current_rating, inclusion: { in: [true, false] }

  def human_rating
    return 'negative' if rating.negative?
    return 'positive' if rating.positive?

    'neutral'
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include CommentStateMachine
  extend Enumerize

  enumerize :rating, in: { positive: 1, neutral: 0, negative: -1 }

  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend Enumerize

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enumerize :role, in: [:user, :admin], default: :user, predicates: true

  has_many :comments, dependent: :destroy
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/web/admin/application_controller.rb
# frozen_string_literal: true

class Web::Admin::ApplicationController < Web::ApplicationController
  before_action :authenticate_admin!

  def authenticate_admin!
    return redirect_to root_path unless admin_signed_in?
  end

  def admin_signed_in?
    current_user.admin?
  end
end

app/controllers/web/admin/articles_controller.rb
# frozen_string_literal: true

class Web::Admin::ArticlesController < Web::Admin::ApplicationController
  def index
    @articles = Article.includes(:ratings).where('article_ratings.article_id IS NULL OR article_ratings.is_current_rating = ?', true).references(:ratings)
  end

  def show
    article
  end

  def edit
    article
  end

  def update
    article_form = article.becomes(Admin::UpdateArticleForm)

    if article_form.update(article_params)
      redirect_to action: :index
    else
      @article = article_form.becomes(Article)
      render :edit
    end
  end

  def destroy
    article.destroy

    redirect_to action: :index
  end

  def publish
    if article.publish!
      redirect_to action: :index
    else
      render :edit
    end
  end

  def archive
    if article.archive!
      redirect_to action: :index
    else
      render :edit
    end
  end

  private

  def article_params
    params.require(:article)
  end

  def article
    @article ||= Article.find(params[:id])
  end
end

app/controllers/web/admin/comments/application_controller.rb
# frozen_string_literal: true

class Web::Admin::Comments::ApplicationController < Web::Admin::ApplicationController
  def current_comment
    @current_comment ||= Comment.find(params[:comment_id])
  end

  def current_article
    @current_article = current_comment.article
  end
end

app/controllers/web/admin/comments/ratings_controller.rb
# frozen_string_literal: true

class Web::Admin::Comments::RatingsController < Web::Admin::Comments::ApplicationController
  def update
    comment_rating_form = current_comment.becomes(Comment::RatingForm)
    comment_mutator = Comment::RatingMutator.update(comment_rating_form, rating_params)

    if comment_mutator.valid?
      redirect_to admin_comments_path
    else
      @comment = comment_mutator.becomes(Comment)
      render :edit
    end
  end

  private

  def rating_params
    params.require(:comment)
  end
end

app/controllers/web/admin/comments_controller.rb
# frozen_string_literal: true

class Web::Admin::CommentsController < Web::Admin::ApplicationController
  def index
    @comments = Comment.pending_review
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  include Pundit
end

app/controllers/web/articles/application_controller.rb
# frozen_string_literal: true

class Web::Articles::ApplicationController < Web::ApplicationController
  before_action :authenticate_user!

  def current_article
    @current_article ||= Article.published.find(params[:article_id])
  end
end

app/controllers/web/articles/comments_controller.rb
# frozen_string_literal: true

class Web::Articles::CommentsController < Web::Articles::ApplicationController
  def create
    @comment = current_article.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to article_path(current_article)
    else
      render 'web/comments/new', locals: { article: current_article }
    end
  end

  def destroy
    comment = current_article.comments.find(params[:id])

    authorize([:article, comment])

    comment.destroy

    redirect_to article_path(current_article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/web/articles_controller.rb
# frozen_string_literal: true

class Web::ArticlesController < Web::ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.published
  end

  def show
    article
  end

  def new
    @article = Article.new
  end

  def create
    article_form = ArticleForm.new(article_params)
    article_form.user = current_user

    if article_form.save
      redirect_to action: :index
    else
      @article = article_form.becomes(Article)
      render :new
    end
  end

  def edit
    article
  end

  def update
    article_form = article.becomes(ArticleForm)

    authorize(article)

    if article_form.update(article_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    authorize(article)

    article.destroy

    redirect_to action: :index
  end

  private

  def article_params
    params.require(:article)
  end

  def article
    @article ||= Article.published.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    = render "layouts/shared/head"
  body.d-flex.flex-column.h-100
    = render "layouts/shared/nav"

    .container.my-5
      main
        = yield
    = render "layouts/shared/footer"

app/views/layouts/shared/_footer.html.slim
footer.bg-light.border-top.mt-auto.py-3.px-5
  ' Test Project

app/views/layouts/shared/_head.html.slim
title
  | DbWorkshopComplexityManagement
meta[name="viewport" content="width=device-width,initial-scale=1"]
= csrf_meta_tags
= csp_meta_tag
/ = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.flex-shrink-0.border-bottom
  - if user_signed_in?
    ul.nav.mr-auto
      li.nav-item.dropdown
        a.nav-link.dropdown-toggle role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          | Actions
        .dropdown-menu aria-labelledby="navbarDropdown"
          = link_to "New Article", new_article_path, class: "dropdown-item"
  ul.nav.ml-auto
    - if user_signed_in?
      li.nav-item.ml-2
        = link_to "Sing Out", destroy_user_session_path, class: "btn btn-primary", method: :delete
    - else
      li.nav-item
        = link_to "Sing In", new_user_session_path, class: "btn btn-outline-primary"
      li.nav-item.ml-2
        = link_to "Sing Up", new_user_registration_path, class: "btn btn-primary"

app/views/layouts/shared/admin/_head.html.slim
title
  | Admin DbWorkshopComplexityManagement
meta[name="viewport" content="width=device-width,initial-scale=1"]
= csrf_meta_tags
= csp_meta_tag
/ = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/shared/admin/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.flex-shrink-0.border-bottom
  ul.nav.mr-auto
    li.nav-item.dropdown
      a.nav-link.dropdown-toggle role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
        | Actions
      .dropdown-menu aria-labelledby="navbarDropdown"
        = link_to "Articles", admin_articles_path, class: "dropdown-item"
        = link_to "Comments", admin_comments_path, class: "dropdown-item"
        = link_to "Sing Out", destroy_user_session_path, class: "dropdown-item", method: :delete

app/views/layouts/web/admin/application.html.slim
doctype html
html.h-100
  head
    = render "layouts/shared/admin/head"
  body.d-flex.flex-column.h-100
    = render "layouts/shared/admin/nav"

    .container.my-5
      main
        = yield
    = render "layouts/shared/footer"

app/views/web/admin/articles/_form.html.slim
= simple_form_for(article, url: admin_article_path(article)) do |f|
 = f.input :title
 = f.input :body
 = f.association :category
 = f.button :submit

app/views/web/admin/articles/edit.html.slim
h1 Edit Article

= render "form", article: @article

app/views/web/admin/articles/index.html.slim
h1 Articles

table class="table"
  thead
    tr
      th scope="col"
        | Title
      th scope="col"
       | Rating
  tbody
    - @articles.each do |article|
      tr
        td
          = link_to article.title, admin_article_path(article)
        td
          = article.ratings.first&.human_rating

app/views/web/admin/articles/show.html.slim
h2
  = @article.title
  span class="badge bg-primary ml-3"
    = @article.state

p
  = @article.body

.btn-group
  = link_to "Edit", edit_admin_article_path(@article), class: "btn btn-outline-primary"
  = link_to "Destroy", admin_article_path(@article), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" }

  - if !@article.published? && !@article.archived?
    = link_to "Publish", publish_admin_article_path(@article), method: :patch, class: "btn btn-outline-success", data: { confirm: "Are you sure?" }

  - if !@article.archived?
    = link_to "Archive", archive_admin_article_path(@article), method: :patch, class: "btn btn-outline-secondary", data: { confirm: "Are you sure?" }

app/views/web/admin/comments/index.html.slim
h1 Comments

- @comments.each do |comment|
  .card.mb-3
    .card-header.d-flex
      .mr-auto
        | Commenter:
        '
        = comment.user&.email

    .card-body
      p class="card-text"
        = comment.body
        = render "web/admin/comments/ratings/form", comment: comment

app/views/web/admin/comments/ratings/_form.html.slim
= simple_form_for comment, url: admin_comment_rating_path(comment), wrapper: :inline_form, html: { class: "form-inline" } do |f|
  label class="form-label mr-3" Rating
  = f.input :rating, as: :select, collection: Comment.rating.options
  = f.button :submit, "Save", class: "btn btn-outline-primary ml-3"

app/views/web/admin/comments/ratings/edit.html.slim
.card.mb-3
  .card-header.d-flex
    .mr-auto
      | Commenter:
      '
      = @comment.user&.email

  .card-body
    p class="card-text"
      = @comment.body
      = render "form", comment: @comment

app/views/web/articles/_form.html.slim
= simple_form_for article do |f|
 = f.input :title
 = f.input :body
 = f.association :category
 = f.button :submit

app/views/web/articles/edit.html.slim
h1 Edit Article

= render "form", article: @article

app/views/web/articles/index.html.slim
h1 Articles

div
  - @articles.each do |article|
    .row class=["mb-4"]
      .col
        h2
          = link_to article.title, article

        = link_to "Read More", article, class: "btn btn-outline-primary"

app/views/web/articles/new.html.slim
h1 New Article

= render "form", article: @article

app/views/web/articles/show.html.slim
h1
  = @article.title
i
  | Author
  '
  = @article.user.email
p
  = @article.body

.btn-group.mb-5
  - if policy(@article).update?
      = link_to "Edit", edit_article_path(@article), class: "btn btn-outline-primary"

  - if policy(@article).destroy?
      = link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger"

h2 Comments
= render @article.comments

- if user_signed_in?
  h2 Add a comment:
  = render "web/comments/form", article: @article, comment: @article.comments.build

app/views/web/comments/_comment.html.slim
.card.mb-3
  .card-header.d-flex
    .mr-auto
      | Commenter:
      '
      = comment.user&.email

    - if user_signed_in? && policy([:article, comment]).destroy?
      .ml-auto
        = link_to [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-light" do
          = octicon "trash", :height => 24
  .card-body
    p class="card-text"
      = comment.body

app/views/web/comments/_form.html.slim
= simple_form_for [article, comment] do |f|
  = f.error_notification
  = f.input :body
  = f.submit

app/views/web/comments/new.html.slim
h1 New Comment

= render "web/comments/form", article: article, comment: @comment